# Generated by Django 3.0.4 on 2020-03-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_breed_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='excercise_needs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], unique=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='friendliness',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], unique=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='shedding_amount',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], unique=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='trainability',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], unique=True),
        ),
    ]
